blueprint:
  name: Alarm Lights with Dynamic Speakers
  description: Trigger alarms with lights, sound, and notifications based on motion and device events, with dynamic speaker selection.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor to trigger the alarm.
      selector:
        entity:
          domain: binary_sensor
    device_sensor:
      name: Device Sensor
      description: Device sensor to trigger the alarm.
      selector:
        entity:
          domain: binary_sensor
    alarm_condition:
      name: Alarm Condition
      description: Input boolean to arm the intruder alarm.
      selector:
        entity:
          domain: input_boolean
    media_players:
      name: Media Players
      description: Media players to use for alarm sounds.
      selector:
        target:
          entity:
            domain: media_player
    notification_device:
      name: Notification Device
      description: Mobile device to receive notifications.
      selector:
        device:
    alert_lights:
      name: Alert Lights
      description: Lights to turn on for the alarm.
      selector:
        target:
          entity:
            domain: light
    alert_playlist:
      name: Alert Playlist
      description: Spotify playlist URL to play during the alarm.
      selector:
        text:
    flash_lights:
      name: Flash Lights
      description: Lights to flash during the alarm.
      selector:
        target:
          entity:
            domain: light
