blueprint:
  name: Kill Alarm
  description: A blueprint to disable the alarm, stop media playback, and turn off lights.
  domain: automation
  input:
    kill_button:
      name: Kill Alarm Button
      description: The input button to trigger the alarm shutdown.
      selector:
        entity:
          domain: input_button
    alarm_automation:
      name: Alarm Automation
      description: The automation to turn off and reset.
      selector:
        entity:
          domain: automation
    media_areas:
      name: Media Player Areas
      description: Areas containing media players to stop playback and clear playlists.
      selector:
        target:
          area: {}
    light_areas:
      name: Light Areas
      description: Areas containing lights to turn off after the alarm is killed.
      selector:
        target:
          area: {}

trigger:
  - platform: state
    entity_id: !input kill_button

condition: []

action:
  - service: automation.turn_off
    target:
      entity_id: !input alarm_automation
    data:
      stop_actions: true
  - service: automation.turn_on
    target:
      entity_id: !input alarm_automation
  - parallel:
      - service: media_player.media_stop
        target: !input media_areas
      - service: media_player.clear_playlist
        target: !input media_areas
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
  - service: light.turn_off
    target:
      area_id: !input light_areas

